# Generated by Django 5.0.3 on 2024-03-29 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_trade_take_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='actual_loss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='actual_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='after_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='before_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='commissions_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='emotions_during_trade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='position_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='risk_reward_ratio',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stop_loss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.strategy'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='targeted_loss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='targeted_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='time_frame',
            field=models.CharField(blank=True, choices=[('15min', '15min'), ('30min', '30min'), ('45min', '45min'), ('1hr', '1hr'), ('2hr', '2hr'), ('3hr', '3hr'), ('4hr', '4hr'), ('1D', '1D')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_result',
            field=models.CharField(blank=True, choices=[('WIN', 'WIN'), ('LOSS', 'LOSS'), ('BE', 'BREAK_EVEN'), ('DEFAULT', 'DEFAULT')], default=('DEFAULT', 'DEFAULT'), max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='type_of_trade',
            field=models.CharField(blank=True, choices=[('Long', 'Long'), ('Short', 'short')], default=None, max_length=10, null=True),
        ),
    ]
