# Generated by Django 5.0.3 on 2024-03-30 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('server_name', models.CharField(blank=True, max_length=100, null=True)),
                ('type_option', models.CharField(blank=True, max_length=100, null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('leverage', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('market', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('wins_hit_tp', models.IntegerField(blank=True, null=True)),
                ('wins_break_even', models.IntegerField(blank=True, null=True)),
                ('break_even', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_fee', models.IntegerField(blank=True, null=True)),
                ('type_of_trade', models.CharField(blank=True, choices=[('Long', 'Long'), ('Short', 'short')], default=None, max_length=10, null=True)),
                ('take_profit', models.IntegerField(blank=True, null=True)),
                ('stop_loss', models.IntegerField(blank=True, null=True)),
                ('risk_reward_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True)),
                ('targeted_profit', models.IntegerField(blank=True, null=True)),
                ('targeted_loss', models.IntegerField(blank=True, null=True)),
                ('time_frame', models.CharField(blank=True, choices=[('15min', '15min'), ('30min', '30min'), ('45min', '45min'), ('1hr', '1hr'), ('2hr', '2hr'), ('3hr', '3hr'), ('4hr', '4hr'), ('1D', '1D')], default=None, max_length=255, null=True)),
                ('emotions_during_trade', models.TextField(blank=True, null=True)),
                ('position_size', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('before_screenshot', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('entry_date', models.DateTimeField()),
                ('exit_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trading.account')),
                ('asset_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading.asset')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='TradeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('after_screenshot', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('trade', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.trade')),
            ],
        ),
    ]
