# Generated by Django 5.0.3 on 2024-03-29 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=10)),
                ('commissions_fees', models.IntegerField()),
                ('description', models.TextField()),
                ('type_of_trade', models.CharField(choices=[('Long', 'Long'), ('Short', 'short')], default=None, max_length=10)),
                ('take_profit', models.IntegerField()),
                ('stop_loss', models.IntegerField()),
                ('risk_reward_ratio', models.DecimalField(decimal_places=3, max_digits=3)),
                ('targeted_profit', models.IntegerField()),
                ('targeted_loss', models.IntegerField()),
                ('actual_profit', models.IntegerField()),
                ('actual_loss', models.IntegerField()),
                ('trade_result', models.CharField(choices=[('WIN', 'WIN'), ('LOSS', 'LOSS'), ('BE', 'BREAK_EVEN'), ('DEFAULT', 'DEFAULT')], default=('DEFAULT', 'DEFAULT'), max_length=255)),
                ('time_frame', models.CharField(choices=[('15min', '15min'), ('30min', '30min'), ('45min', '45min'), ('1hr', '1hr'), ('2hr', '2hr'), ('3hr', '3hr'), ('4hr', '4hr'), ('1D', '1D')], default=None, max_length=255)),
                ('emotions_during_trade', models.TextField()),
                ('position_size', models.DecimalField(decimal_places=2, max_digits=3)),
                ('before_screenshot', models.ImageField(upload_to='media/')),
                ('after_screenshot', models.ImageField(upload_to='media/')),
                ('entry_date', models.DateTimeField()),
                ('exit_date', models.DateTimeField()),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.strategy')),
            ],
        ),
    ]
