# Generated by Django 5.0.4 on 2024-05-15 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderesult',
            name='account',
        ),
        migrations.AddField(
            model_name='trade',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trading.account'),
        ),
    ]
