# Generated by Django 5.0.6 on 2024-05-20 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_remove_traderesult_account_trade_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='before_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='media/trades'),
        ),
        migrations.AlterField(
            model_name='traderesult',
            name='after_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='media/trades/trade_results'),
        ),
        migrations.AlterField(
            model_name='traderesult',
            name='trade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='trading.trade'),
        ),
    ]
