# Generated by Django 5.0.3 on 2024-04-15 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_accountbalance_deposit_withdraw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountBalance',
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deposit',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trading.account'),
        ),
        migrations.AddField(
            model_name='traderesult',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trading.account'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trading.account'),
        ),
    ]
