# Generated by Django 5.0.3 on 2024-03-29 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_trade_actual_loss_alter_trade_actual_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='commissions_fees',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='strategy',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='journal.strategy'),
        ),
    ]
