# Generated by Django 5.0.3 on 2024-03-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_strategy_name_alter_trade_commissions_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='take_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
