# Generated by Django 5.0.3 on 2024-04-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_alter_deposit_amount_alter_withdraw_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderesult',
            name='is_won',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
