# Generated by Django 5.0.3 on 2024-04-15 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_traderesult_is_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trading.broker'),
        ),
    ]
