# Generated by Django 5.0.3 on 2024-04-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_account_broker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='break_even',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='wins_break_even',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='wins_hit_tp',
        ),
        migrations.AddField(
            model_name='strategy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
