# Generated by Django 5.0.3 on 2024-04-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_remove_strategy_break_even_remove_strategy_losses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderesult',
            name='account',
        ),
    ]
