# Generated by Django 5.0.3 on 2024-04-15 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_remove_traderesult_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='account_id',
        ),
        migrations.AddField(
            model_name='traderesult',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trading.account'),
        ),
    ]
