# Generated by Django 5.0.3 on 2024-04-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_remove_trade_account_id_traderesult_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='exit_date',
        ),
        migrations.AddField(
            model_name='traderesult',
            name='exit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
