# Generated by Django 5.0.6 on 2024-06-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options_user_ispro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isPro',
        ),
    ]
